export const driverRegistry: Record<string, string> = {
  "K Larson": "Kyle Larson",
  "B Wallace": "Bubba Wallace",
  "T Gilliland": "Todd Gilliland",
  "D Suarez": "Daniel Suarez",
  "J Berry": "Josh Berry",
  "C Elliott": "Chase Elliott",
  "A Cindric": "Austin Cindric",
  "T Barron": "Travis Barron",
  "K Busch": "Kyle Busch",
  "C Briscoe": "Chase Briscoe",
  "W Byron": "William Byron",
  "R Chastain": "Ross Chastain",
  "T Reddick": "Tyler Reddick",
  "D Hamlin": "Denny Hamlin",
  "C Buescher": "Chris Buescher",
  "C Hocevar": "Carson Hocevar",
  "C Bell": "Christopher Bell",
  "A Alfredo": "Anthony Alfredo",
  "J Haley": "Justin Haley",
  "J Nemechek": "John Hunter Nemechek",
  "J Logano": "Joey Logano",
  "E Jones": "Erik Jones",
  "A Bowman": "Alex Bowman",
  "M Truex, Jr.": "Martin Truex, Jr.",
  "T Gibbs": "Ty Gibbs",
  "C LaJoie": "Corey Lajoie",
  "S van Gisbergen": "Shane van Gisbergen",
  "C Ware": "Cody Ware",
  "D Hemric": "Daniel Hemric",
  "N Gragson": "Noah Gragson",
  "Z Smith": "Zane Smith",
  "A Dillon": "Austin Dillon",
  "B Keselowski": "Brad Keselowski",
  "R Preece": "Ryan Preece",
  "H Burton": "Harrison Burton",
  "B McLeod": "BJ McLeod",
  "R Stenhouse, Jr.": "Ricky Stenhouse, Jr.",
  "M McDowell": "Michael McDowell"
}